[book]
authors = ["Xavier2p"]
language = "en"
multilingual = false
src = "src"
title = "Documentation | Helix"
description = "The documentation of the Helix Project"

[rust]
edition = "2021"


[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/helix-medical"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
