site_name: Helix | Documentation

theme:
    name: material
    language: en
    palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          toggle:
              icon: material/toggle-switch
              name: Switch to dark mode
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: teal
          accent: teal
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to light mode
    favicon: assets/favicon.png
    logo: assets/favicon.png
    features:
        - navigation.tabs.sticky
        - navigation.instant
        - navigation.path
    icon:
        repo: fontawesome/brands/github

repo_name: helix-medical/helix
repo_url: https://github.com/helix-medical/docs
