site_name: Helix | Documentation
site_description: The official documentation for the Helix project
site_author: Xavier2p
site_url: https://helix-medical.github.io/docs

theme:
    name: material
    language: en
    palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: teal
          toggle:
              icon: material/toggle-switch
              name: Switch to dark mode
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: teal
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to light mode
    favicon: assets/favicon.png
    logo: assets/favicon.png
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.path
        - toc.integrate
        - navigation.top
        - navigation.expand
        - toc.follow
        - content.code.copy
        - navigation.footer
        - content.tooltip
        - navigation.indexes
    icon:
        repo: fontawesome/brands/github

repo_name: helix-medical/releases
repo_url: https://github.com/helix-medical/releases
copyright: Copyright &copy; 2023 Helix Medical

plugins:
    - search:
          lang: fr

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Xavier2p
          name: GitHub
        - icon: fontawesome/brands/docker
          link: https://hub.docker.com/u/xavier2p
          name: Docker Hub
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/xavier-de-place
          name: LinkedIn
        - icon: fontawesome/solid/envelope
          link: mailto:contact.helix@skiff.com
          name: Skiff Mail

markdown_extensions:
    - admonition
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid

nav:
    - Home: index.md
    - Getting Started:
          - getting-started/index.md
          - Disclaimer: getting-started/disclaimer.md
          - Installation: getting-started/install.md
          - Configuration: getting-started/configuration.md
          - Usage: getting-started/usage.md
    - API:
          - api/index.md
          - Schema: api/schema.md
          - Events: api/events.md
          - Patients: api/patients.md
          - Appointments: api/appointments.md
          - Accounting: api/accounting.md
          - Users: api/users.md
          - Auth: api/auth.md
