---
name: Build and Deploy Helix Website

on:
  push:
    paths:
      - website/**

permissions:
  contents: write
  packages: write

jobs:
  static:
    name: Deploy static website on GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        working-directory: website
        run: npm ci && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist

  package:
    name: Build Docker image for Helix Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./website.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/xavier2p/helix-website
