name: Deploy the Helix Documentation to GitHub Wiki

on:
  push:
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    name: Publish to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Documentation
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs
          commit-message: Update Wiki from ${{ github.sha }}
